version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./config/vhosts:/etc/apache2/sites-available:delegated
    ports:
      - '80:80'
    environment:
      PHP_ENABLE_XDEBUG: 1
  db_mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8080:8080