<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Created at' => 'Создан',
    'Updated at' => 'Обновлён',
    'Announce' => 'Анонс',
    'Are you sure you want to delete this item?' => 'Вы действительно хотите удалить эту запись?',
    'Author' => 'Автор',
    'Author ID' => 'ID автора',
    'Blog' => 'Блог',
    'Categories' => 'Категории',
    'Category' => 'Категория',
    'Category ID' => 'ID категории',
    'Comments' => 'Комментарии',
    'Content' => 'Контент',
    'Create' => 'Создать',
    'Create Category' => 'Создать категорию',
    'Create Comment' => 'Создать комментарий',
    'Create Post' => 'Создать пост',
    'Create User' => 'Создать пользователя',
    'Delete' => 'Удалить',
    'Draft' => 'Черновик',
    'Email' => 'E-mail',
    'Home' => 'Главная',
    'ID' => 'ID',
    'Login' => 'Вход',
    'Logout ({username})' => 'Выход ({username})',
    'Moderate' => 'На модерации',
    'My Yii Blog' => 'Мой Yii Блог',
    'New Password' => 'Новый пароль',
    'Pid' => 'PID',
    'Please fill out the following fields to login:' => 'Пожалуйста заполните следующие поля для входа:',
    'Post ID' => 'ID поста',
    'Posts' => 'Посты',
    'Publish' => 'Опубликован',
    'Publish date' => 'Дата публикации',
    'Publish status' => 'Статус',
    'Published' => 'Опубликован',
    'Role' => 'Роль',
    'Site' => 'Сайт',
    'Status' => 'Статус',
    'Tag ID' => 'Тэг ID',
    'Tags' => 'Тэги',
    'Title' => 'Заголовок',
    'Update' => 'Обновить',
    'Update Category:' => 'Обновить категорию:',
    'Update Comment:' => 'Обновить комментарий:',
    'Update Post:' => 'Обновить пост:',
    'Update User:' => 'Редактировать пользователя:',
    'Username' => 'Имя пользователя',
    'Users' => 'Пользователи',
];
