<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Вы действительно хотите удалить эту запись?',
    'Create' => 'Создать',
    'Create Category' => 'Создать категорию',
    'Delete' => 'Удалить',
    'Update' => 'Обновить',
    'Update Category:' => 'Обновить категорию',
    'Announce' => 'Анонс',
    'Author' => 'Автор',
    'Author ID' => 'ID автора',
    'Categories' => 'Категории',
    'Category' => 'Категория',
    'Category ID' => 'ID категории',
    'Content' => 'Контент',
    'ID' => 'ID',
    'Pid' => 'PID',
    'Post ID' => 'ID поста',
    'Publish date' => 'Дата публикации',
    'Publish status' => 'Статус',
    'Tag ID' => 'Тэг ID',
    'Tags' => 'Тэги',
    'Title' => 'Заголовок',
];
