<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Body' => 'Сообщение',
    'E-mail' => 'E-mail',
    'If you forgot your password you can' => 'Если вы забыли пароль, вы можете',
    'Name' => 'Имя',
    'Please choose your new password' => 'Пожалуйста задайте ваш новый пароль',
    'Please contact us if you think this is a server error. Thank you.' => 'Пожалуйста сообщите нам, если вы видите эту ошибку. Спасибо.',
    'Please fill out the following fields to login' => 'Пожалуйста заполните следующие поля для входа',
    'Please fill out the following fields to signup' => 'Пожалуйста заполните следующие поля для регистрации',
    'Please fill out your email. A link to reset password will be sent there.' => 'Пожалуйста заполните E-mail. На него будет отправлена ссылка для сброса пароля',
    'Request password reset' => 'Запрос сброса пароля',
    'Reset password' => 'Сбросить пароль',
    'Save' => 'Сохранить',
    'Send' => 'Отправить',
    'Subject' => 'Тема',
    'The above error occurred while the Web server was processing your request.' => 'Произошла ошибка сервера во время обработки вашего запроса.',
    'This is the About page. You may modify the following file to customize its content' => 'Это страница "О мне". Вы можете её модифицировать по следующему пути',
    'Verification Code' => 'Проверочный код',
    'About' => 'О мне',
    'Administration' => 'Админ-панель',
    'Author' => 'Автор',
    'Blog' => 'Блог',
    'Categories' => 'Категории',
    'Category' => 'Категория',
    'Contact' => 'Контакты',
    'Login' => 'Вход',
    'Logout ({username})' => 'Выход ({username})',
    'More' => 'Читать далее',
    'Posts' => 'Посты',
    'Publish' => 'Опубликован',
    'Publish date' => 'Дата публикации',
    'Sign up' => 'Регистрация',
    'Submit' => 'Отправить',
    'Tags' => 'Тэги',
    'Tag' => 'Тэг',
];
